#!/usr/bin/env node
'use strict';

let program = require('commander')

program
    .version('0.0.1')
    .command('login-test', 'do a test login')
    .command('entry-post', 'post a new entry')
    .parse(process.argv)
