#!/usr/bin/env node
'use strict';

let program = require('commander')
let cli = require('./lib/cli')

cli.cridentials_export()

program
    .version(cli.meta.version)
    .option('-n, --netrc <string>', 'a path to a .netrc',
	    cli.cridentials_export)
    .command('login-test', 'do a test login')
    .command('entry-post', 'post a new entry')
    .parse(process.argv)
