#!/usr/bin/env node
'use strict';

let program = require('commander')
let cli = require('./lib/cli')
let version = require('./lib/dreamwidth').user_agent()

cli.cridentials_export()

program
    .version(version)
    .option('--debug', '(ignore)', () => {
	process.env.dw_debug = 1
    })
    .option('-n, --netrc <string>', 'a path to a .netrc',
	    cli.cridentials_export)
    .command('login-test', 'do a test login')
    .command('entry-post', 'post a new entry (w/ html as the input)')
    .command('entry-post-md', 'post a new entry (w/ markdown as the input)')
    .command('img-upload', 'upload an image')
    .parse(process.argv)
