#!/usr/bin/env node
'use strict';

let cp = require('child_process')

let program = require('commander')
let concat = require('concat-stream')
let fetch = require('node-fetch')
let FormData = require('form-data')

let cli = require('./lib/cli')
let dw = require('./lib/dreamwidth')

let mime = function(input) {
    let kid = cp.spawnSync('file', ['-b', '--mime-type', '-'], {
	input: input,
	timeout: 10 * 1000,
    })
    if (kid.status !== 0)
	cli.errx('failed to determine the mime type'
		 + (kid.error ? `: ${kid.error}` : ''))
    return kid.stdout.toString()
}

program
    .usage('[options] < file.jpg')
    .option('-u, --res-url', 'print just an img url after the upload')
    .parse(process.argv)

let journal = new dw.Dreamwidth(process.env.dw_login, process.env.dw_password)
let session = new dw.Session(journal)
session.log = cli.perrx

process.stdin.pipe(concat( input => {
    if (!input.length) cli.errx('invalid input')

    let form = new FormData()
    form.append('files', input, {
	// we need to set the content-type explicitly for we provide
	// to FormData just a buffer instead of a readable stream (w/
	// path, from which FormData would have been able to determine
	// content-type by itself)
	contentType: mime(input),
    })

    session.get().then( sid => {
	return fetch('https://www.dreamwidth.org/api/v1/file/new', {
	    method: 'POST',
	    headers: {
		cookie: `ljsession=${encodeURIComponent(sid)}`,
	    },
	    body: form,
	})
    }).then( res => res.json()).then( json => {
	if (program.resUrl && json.result && json.result.url) {
	    console.log(json.result.url)
	} else {
	    console.log(json)
	}

	if (json.success !== 1) process.exit(1)

    }).catch( err => {
	cli.errx(err)
    })

}))
