#!/usr/bin/env node
'use strict';

let spawn = require('child_process').spawn

let marked = require('marked')
let fm = require('front-matter')
let commander = require('commander')
let concat = require('concat-stream')

let cli = require('./lib/cli')

let md_parse = function(input) {
    let params = fm(input)
    let r = { args: [] }
    for (let key in params.attributes) {
	let val = params.attributes[key]
	if (val) r.args.push('--' + key.toLowerCase(), val)
    }

    r.body = marked(params.body)
    return r
}

commander.parse(process.argv) // it's here only for reacting on -h

process.stdin.pipe(concat( input => {
    input = input.toString()
    let params = md_parse(input)
    if (process.env.dw_debug) console.log(params)

    let kid = spawn(__dirname + '/dreamwidth-js-entry-post', params.args,
		    { stdio: ['pipe', 'inherit', 'inherit'] })
    kid.on('close', process.exit)
    kid.on('error', cli.errx)
    kid.stdin.write(params.body)
    kid.stdin.end()

}))
