#!/usr/bin/env node
'use strict';

let program = require('commander')

let cli = require('./lib/cli')
let dw = require('./lib/dreamwidth')

program.parse(process.argv)

let journal = new dw.Dreamwidth(process.env.dw_login, process.env.dw_password)

journal.login().then( () => {
    return journal.login_test()
}).then( val => {
    console.log(val)
}).catch( err => {
    cli.abort(err)
})
