#!/usr/bin/env node
'use strict';

let program = require('commander')
let concat = require('concat-stream')

let cli = require('./lib/cli')
let dw = require('./lib/dreamwidth')

program
    .usage('[options] < file.html')
    .option('-s, --subject <string>', 'entry title')
    .option('-d, --date <string>', 'YYYY-MM-DD HH:MM')
    .option('-t, --tags <string>', 'tags separated by commas')
    .option('--backdated', "don't show up on people's friends lists")
    .option('--security <string>', 'private, public', 'private')
    .parse(process.argv)

process.stdin.pipe(concat( input => {
    input = input.toString()
    if (!input.trim().length) cli.errx('invalid input')

    let jrn = new dw.Dreamwidth(process.env.dw_login, process.env.dw_password)
    jrn.debug = !!process.env.dw_debug
    program.date = new Date(Date.parse(program.date) || Date.now())

    jrn.entry_post(program.subject, program.date, program.tags,
		   input, {
		       opt_backdated: program.backdated,
		       security: program.security
		   })
	.then( val => {
	    console.log(val)
	}).catch( err => {
	    cli.abort(err)
	})

}))
